let puntaje = 5;
puntaje++; //5
//ESTO PORQUE PRIMERO
//SE EJECUTA PUNTAJE
//ENTOCEN SE TIENE QUE VOLVER A 
//LLAMAR PARA QUE EL IMCREMENTO SE
//CUMPLA

++puntaje;//6
//AQUI EL IMCREMENTO 
//LO HACE POR AUTOMATICO 
//YA QUE PRIMERO
//SE EJECUTA LA FUNCION
//DE INCREMENTO

//IMPEMENTOS MAS ELEVADOS

let puntaje2 = 5
puntaje2 +=3
puntaje2 -=2
console.log(puntaje2)
